name: QuantumX papers

on:
  schedule:
    - cron: '0 13 * * MON'    # every Monday 06:00 Seattle time
  workflow_dispatch: {}        # allows manual “Run workflow”

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install -r requirements.txt
      - run: python qx_harvest.py
      - name: Commit & push results
        run: |
          git config user.name  "qx-bot"
          git config user.email "qx-bot@users.noreply.github.com"
          git add digest.md digest.bib || true
          git commit -m "update $(date +'%F')" || echo "Nothing to commit"
          git push
